name: Lint the code

on:
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**/README.md'
jobs:
  build:
    name: lint the dart code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
      - run: flutter --version
      - run: flutter pub get
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v2
        with:
          fail-on-warnings: true